simple_base:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10  

  # Position Controllers
  joint_position_controller:
    type: velocity_controllers/JointPositionController
    joint: joint
    pid: {p: 1.0, i: 0.1, d: 0}
