simple_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10  

  # Position Controllers ---------------------------------------
  joint_position_controller:
    type: position_controllers/JointPositionController
    joint: joint
    pid: {p: 1.0, i: 0.0, d: 0}

